#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bafa[-1]
	add ucitrack bafa
	set ucitrack.@bafa[-1].init=bafa
	commit ucitrack
EOF

chmod +x /etc/init.d/bafa
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
