#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/stdoutsubc

check_log() {
	pgrep -f bafa_checklog | xargs kill -9 >/dev/null 2>&1

  cat > /tmp/bafa_checklog<<'EOF'
#!/bin/sh

while true; do
	if [ -f /var/log/bafa.log ]; then
        	LOG_SIZE=$(stat -c%s /var/log/bafa.log)
        	LOG_SIZE_KB=$((LOG_SIZE / 1024))

        	if [ "$LOG_SIZE_KB" -gt 2048 ]; then
            		tail -n 100 /var/log/bafa.log > /var/log/bafa.log.tmp
            		mv /var/log/bafa.log.tmp /var/log/bafa.log
        	fi
        fi
sleep 3600
done
EOF
	chmod +x /tmp/bafa_checklog
	procd_open_instance bafa_checklog
	procd_set_param respawn
	procd_set_param command /tmp/bafa_checklog
	procd_set_param respawn
	procd_close_instance
}

start_instance() {
	local cfg="$1"
    	config_get_bool enabled "$cfg" 'enabled' '0'
    	config_get_bool showtopics "$cfg" 'showtopics' '0'
    	config_get host "$cfg" 'host' 
    	config_get port "$cfg" 'port'
    	config_get topics "$cfg" 'topics'
    	config_get clientid "$cfg" 'clientid'
    	config_get qos "$cfg" 'qos' 
    	config_get username "$cfg" 'username'
    	config_get password "$cfg" 'password'
    	
	[ "$enabled" = "1" ] || return 1
	pgrep -f stdoutsubc | xargs kill -9 >/dev/null 2>&1
	[ -x "$PROG" ] || chmod +x $PROG
	[ -x "/etc/bafayun/bafa.sh" ] || chmod +x /etc/bafayun/bafa.sh
	echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')]：开始启动" >>/var/log/bafa.log
	if [ -z "$topics" ] ; then
		echo "[ERROR] [$(date '+%Y-%m-%d %H:%M:%S')]：订阅的主题名不能为空！" >>/var/log/bafa.log
	fi
	if [ -z "$clientid" ] ; then
		echo "[ERROR] [$(date '+%Y-%m-%d %H:%M:%S')]：账户私钥不能为空！" >>/var/log/bafa.log
	fi
	procd_open_instance bafa
	procd_set_param env TZ=CST-8
	CMD="${topics} --clientid ${clientid}"
	[ -z "$host" ] || CMD="${CMD} --host ${host}"
	[ -z "$port" ] || CMD="${CMD} --port ${port}"
	[ -z "$qos" ] || CMD="${CMD} --qos ${qos}"
	[ -z "$username" ] || CMD="${CMD} --username ${username}"
	[ -z "$password" ] || CMD="${CMD} --password ${password}"
	[ -s "/etc/bafayun/bafa.sh" ] && CMD="${CMD} --script /etc/bafayun/bafa.sh"
	[ "$showtopics" = "1" ] && CMD="${CMD} --showtopics on"
	procd_set_param command /bin/sh -c "${PROG} ${CMD} >> /var/log/bafa.log 2>&1"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	check_log
}

start_service() {
	config_load 'bafa'
	config_foreach start_instance 'bafa'
}

stop_service() {
	pgrep -f bafa_checklog | xargs kill -9 >/dev/null 2>&1
	pgrep -f stdoutsubc | xargs kill -9 >/dev/null 2>&1
	echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')]：停止运行" >/var/log/bafa.log
}

service_triggers() {
      procd_add_reload_trigger "bafa"
}
